spring.application.name=spring_mvc_study1_servlet

logging.level.org.apache.coyote.http11=trace

# viewResolver 설정 -> new-form 와 같으 논리 주소를 /WEB-INF/views/new-form.jsp의 물리 주소로 바꿔줌
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

